root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
rules:
  no-duplicate-imports: error
  no-template-curly-in-string: error
  eqeqeq: error
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars': off
